package practicum.yandex.api;

public enum Endpoints {
    GET_TASKS,
    GET_TASK_BY_ID,
    CREATE_TASK,
    UPDATE_TASK,
    DELETE_TASKS,
    DELETE_TASK_BY_ID,

    GET_SUB_TASKS,
    GET_SUB_TASK_BY_ID,
    CREATE_SUB_TASK,
    UPDATE_SUB_TASK,
    DELETE_SUB_TASKS,
    DELETE_SUB_TASK_BY_ID,

    GET_EPIC_TASKS,
    GET_EPIC_TASK_BY_ID,
    GET_EPIC_SUB_TASKS,
    CREATE_EPIC_TASK,
    UPDATE_EPIC_TASK,
    DELETE_EPIC_TASKS,
    DELETE_EPIC_TASK_BY_ID,

    GET_HISTORY,
    GET_PRIORITIZED_TASKS,

    UNKNOWN
}
